[toolchain]
# REMINDER: After updating the channel, update:
# - docs/src/usage/cargo-miden.md
# - docs/src/usage/midenc.md
channel = "1.91"
components = ["rustfmt", "rust-src", "clippy"]
targets = ["wasm32-unknown-unknown"]
profile = "minimal"
